Controllers/MovimientosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ntt.data.test.luis.pita.Data;
using ntt.data.test.luis.pita.Interfaces;
using ntt.data.test.luis.pita.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace ntt.data.test.luis.pita.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class MovimientosController : Controller
    {
        private readonly ICuenta _cuentaRepo;
        private readonly ITipoCuenta _tipoCuentaRepo;
        private readonly ICliente _clienteRepo;
        private readonly IMovimiento _movimientoRepo;
        private string mensaje = string.Empty;

        public MovimientosController(ICuenta cuentaRepo, ITipoCuenta tipoCuentaRepo, ICliente clienteRepo, IMovimiento movimientoRepo)
        {
            _cuentaRepo = cuentaRepo;
            _tipoCuentaRepo = tipoCuentaRepo;
            _clienteRepo = clienteRepo;
            _movimientoRepo = movimientoRepo;
        }

        [HttpGet("Index")]
        public IActionResult Index()
        {
            IEnumerable<MovimientoModel> lstMovimiento = _movimientoRepo.GetItems();
            return View(lstMovimiento);
        }

        [HttpGet("SelectAll")]
        public IActionResult SelectAll()
        {
            IEnumerable<MovimientoModel> lstMov = _movimientoRepo.GetItems();
            return Ok(lstMov);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            MovimientoModel mov = new MovimientoModel();
            ViewBag.Cuentas = GetCuenta();
            ViewBag.TipoMov = GetTipoMovimiento();
            return View(mov);
        }

        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] MovimientoModel movimiento)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string json = JsonSerializer.Serialize(movimiento);
                    CreateApi(movimiento);
                    if (string.IsNullOrEmpty(mensaje))
                    {
                    TempData["Mensaje"] = "El movimiento se registró correctamente.";
                    return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Mensaje"] = mensaje; 
                        ViewBag.Cuentas = GetCuenta();
                        ViewBag.TipoMov = GetTipoMovimiento();
                    }
                }
                else
                {
                    ViewBag.Cuentas = GetCuenta();
                    ViewBag.TipoMov = GetTipoMovimiento();
                }
                return View();
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpPost("CreateApi")]
        public IActionResult CreateApi(MovimientoModel movimiento)
        {
            try
            {
                ResponseModel response = new ResponseModel();
                decimal valorMov = 0;
                CuentaModel cuenta;

                if (movimiento.TipoMovimiento == "D" && movimiento.Valor > decimal.Parse(GlobalParametro.valorRetiro))
                {
                    response.ErrorId = 1;
                    response.ErrorMensaje = "Excede el valor díario de retiro.";
                    mensaje = response.ErrorMensaje;

                    return Ok(response);
                }

                //Setear la fecha de movimiento
                movimiento.Fecha = DateTime.Now;

                //Obtener en valor del movimiento según tipo
                valorMov = (movimiento.TipoMovimiento == "D" ? (movimiento.Valor * -1) : movimiento.Valor);

                //Consultar saldo de la cuenta
                cuenta = GetCuenta(movimiento.CuentaId);

                if (movimiento.TipoMovimiento == "D" && cuenta.Saldo == 0)
                {
                    response.ErrorId = 1;
                    response.ErrorMensaje = "Saldo no disponible.";
                    mensaje = response.ErrorMensaje;

                    return Ok(response);
                }

                if (movimiento.TipoMovimiento == "D" && cuenta.Saldo < movimiento.Valor)
                {
                    response.ErrorId = 1;
                    response.ErrorMensaje = "Cupo diario excedido.";
                    mensaje = response.ErrorMensaje;

                    return Ok(response);
                }

                //Calcular valores
                movimiento.SaldoInicial = cuenta.Saldo;
                movimiento.Saldo = cuenta.Saldo + valorMov;

                //Crear movimiento
                _movimientoRepo.Create(movimiento);

                //Actualizar saldo de la cuenta
                cuenta.Saldo = movimiento.Saldo;
                _cuentaRepo.Edit(cuenta);

                response.ErrorId = 0;
                response.ErrorMensaje = "El movimiento se registró correctamente.";
                response.root.Add(movimiento);

                return Ok(response);
            }
            catch (Exception ex)
            {
                return Ok(new ResponseModel() { ErrorId = 1, ErrorMensaje = ex.Message });
            }
        }

        [HttpPost("Reporte")]
        public IActionResult Reporte(ReporteModel reporte)
        {
            try
            {
                ResponseModel response = new ResponseModel();
                IEnumerable<MovimientoModel> movimientos = _movimientoRepo.GetItemReporte(reporte);


                response.ErrorId = 0;
                response.ErrorMensaje = "Generación de reporte.";
                response.root.Add(movimientos);

                return Ok(response);
            }
            catch (Exception ex)
            {
                return Ok(new ResponseModel() { ErrorId = 1, ErrorMensaje = ex.Message });
            }
        }

        private List<SelectListItem> GetCuenta()
        {
            var lstCuenta = new List<SelectListItem>();
            List<CuentaModel> cuentas = _cuentaRepo.GetItems().ToList();

            lstCuenta = cuentas.Select(tp => new SelectListItem() { Value = tp.Id.ToString(), Text = tp.Numero + " - " + tp.TipoCuenta.Valor + " - " + tp.Cliente.Persona.Nombre }).ToList();

            return lstCuenta;
        }

        private CuentaModel GetCuenta(int id)
        {
            CuentaModel cuenta = _cuentaRepo.GetItem(id);

            return cuenta;
        }

        private decimal GetSalodCuenta(int idCuenta)
        {
            CuentaModel cuenta = _cuentaRepo.GetItem(idCuenta);
            return cuenta.Saldo;
        }

        private List<SelectListItem> GetTipoMovimiento()
        {
            var lstGenero = new List<SelectListItem>();
            SelectListItem defItem;
            defItem = new SelectListItem() { Value = "C", Text = "Crédito" };
            lstGenero.Insert(0, defItem);

            defItem = new SelectListItem() { Value = "D", Text = "Débito" };
            lstGenero.Insert(1, defItem);

            return lstGenero;
        }

        private List<SelectListItem> GetCliente()
        {
            var lstCliente = new List<SelectListItem>();
            List<ClienteModel> Clientes = _clienteRepo.GetItems().ToList();

            lstCliente = Clientes.Select(tp => new SelectListItem() { Value = tp.Id.ToString(), Text = tp.Persona.Nombre }).ToList();

            return lstCliente;
        }
    }
}

Views/Movimientos/Create.cshtml
@model ntt.data.test.luis.pita.Models.MovimientoModel

@{
    ViewData["Title"] = "Crear movimiento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    @if (TempData["Mensaje"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            @TempData["Mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3>Crear moviemiento</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <form method="post" asp-action="Create">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="CuentaId" class="control-label"></label>
                    <select asp-for="CuentaId" class="form-control" asp-items="ViewBag.Cuentas"></select>
                    <span asp-validation-for="CuentaId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="TipoMovimiento" class="control-label"></label>
                    <select asp-for="TipoMovimiento" class="form-control" asp-items="ViewBag.TipoMov"></select>
                    <span asp-validation-for="TipoMovimiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" class="form-control" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Movimientos/Index.cshtml
@model IEnumerable<ntt.data.test.luis.pita.Models.MovimientoModel>
@{
    ViewData["Title"] = "Lista de Movimientos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["Mensaje"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            @TempData["Mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-md-6">
            <h3>Lista de Movimientos</h3>
        </div>
        <div class="col-md-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Movimientos">Agregar Movimiento</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.Id)</td>
                        <td>@Html.DisplayNameFor(m => m.Fecha)</td>
                        <td>@Html.DisplayNameFor(m => m.Cuenta.Cliente.Persona.Nombre)</td>
                        <td>@Html.DisplayNameFor(m => m.Cuenta.Numero)</td>
                        <td>@Html.DisplayNameFor(m => m.SaldoInicial)</td>
                        <td>@Html.DisplayNameFor(m => m.Cuenta.Estado)</td>
                        <td>@Html.DisplayNameFor(m => m.Valor)</td>
                        <td>@Html.DisplayNameFor(m => m.Saldo)</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Fecha</td>
                            <td>@item.Cuenta.Cliente.Persona.Nombre</td>
                            <td>@item.Cuenta.Numero</td>
                            <td align="right">@item.SaldoInicial.ToString("0.00")</td>
                            <td align="center">@item.Cuenta.Estado</td>
                            @if (@item.TipoMovimiento == "D")
                            {
                                <td align="right"> - @item.Valor.ToString("0.00")</td>
                            }
                            else
                            {
                                <td align="right"> @item.Valor.ToString("0.00")</td>
                            }
                            <td align="right">@item.Saldo.ToString("0.00")</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros.</p>
        }
    </div>
</div>