Controllers/CuentasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ntt.data.test.luis.pita.Data;
using ntt.data.test.luis.pita.Interfaces;
using ntt.data.test.luis.pita.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace ntt.data.test.luis.pita.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class CuentasController : Controller
    {
        private readonly ICuenta _cuentaRepo;
        private readonly ITipoCuenta _tipoCuentaRepo;
        private readonly ICliente _clienteRepo;

        public CuentasController(ICuenta cuentaRepo, ITipoCuenta tipoCuentaRepo, ICliente clienteRepo)
        {
            _cuentaRepo = cuentaRepo;
            _tipoCuentaRepo = tipoCuentaRepo;
            _clienteRepo = clienteRepo;
        }

        [HttpGet("Index")]
        public IActionResult Index()
        {
            IEnumerable<CuentaModel> lstCuentas = _cuentaRepo.GetItems();
            return View(lstCuentas);
        }

        [HttpGet("Select")]
        public IActionResult Select(int cuentaId)
        {
            try
            {
                CuentaModel cuentaReturn = _cuentaRepo.GetItem(cuentaId);
                return Ok(cuentaReturn);
            }
            catch (Exception ex)
            {
                return Ok(new ResponseModel() { ErrorId = 1, ErrorMensaje = ex.Message });
            }
        }

        [HttpGet("SelectAll")]
        public IActionResult SelectAll()
        {
            IEnumerable<CuentaModel> lstCuentas = _cuentaRepo.GetItems();
            return Ok(lstCuentas);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            CuentaModel cuenta = new CuentaModel();
            ViewBag.TipoCuentas = GetTipoCuenta();
            ViewBag.Clientes = GetCliente();
            return View(cuenta);
        }

        [HttpPost("CreateView")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateView([FromForm] CuentaModel cuenta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Create(cuenta);
                    TempData["Mensaje"] = "La cuenta se creó correctamente.";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.TipoCuentas = GetTipoCuenta();
                    ViewBag.Clientes = GetCliente();
                }
                return View();
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpPost("Create")]
        public IActionResult Create(CuentaModel cuenta)
        {
            try
            {
                ResponseModel response = new ResponseModel();

                _cuentaRepo.Create(cuenta);

                response.ErrorId = 0;
                response.ErrorMensaje = "La cuenta se creó correctamente.";
                response.root.Add(cuenta);

                return Ok(response);
            }
            catch (Exception ex)
            {
                return Ok(new ResponseModel() { ErrorId = 1, ErrorMensaje = ex.Message });
            }
        }

        [HttpGet("Edit")]
        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var cuenta = _cuentaRepo.GetItem(Id);

            if (cuenta == null)
            {
                return NotFound();
            }
            ViewBag.TipoCuentas = GetTipoCuenta();
            ViewBag.Clientes = GetCliente();
            return View(cuenta);
        }

        [HttpPost("EditView")]
        [ValidateAntiForgeryToken]
        public IActionResult EditView([FromForm] CuentaModel cuenta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Edit(cuenta);
                    TempData["Mensaje"] = "La cuenta se modificó correctamente.";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.TipoCuentas = GetTipoCuenta();
                    ViewBag.Clientes = GetCliente();
                }
                return View();
            }
            catch (Exception ex)
            {
                return null;
            }
        }


        [HttpPost("Edit")]
        public IActionResult Edit(CuentaModel cuenta)
        {
            try
            {
                ResponseModel response = new ResponseModel();

                _cuentaRepo.Edit(cuenta);

                response.ErrorId = 0;
                response.ErrorMensaje = "La cuenta se modificó correctamente.";
                response.root.Add(cuenta);

                return Ok(response);
            }
            catch (Exception ex)
            {
                return Ok(new ResponseModel() { ErrorId = 1, ErrorMensaje = ex.Message });
            }
        }

        [HttpGet("Delete")]
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var cuenta = _cuentaRepo.GetItem(Id);

            if (cuenta == null)
            {
                return NotFound();
            }
            ViewBag.TipoCuentas = GetTipoCuenta();
            ViewBag.Clientes = GetCliente();
            return View(cuenta);
        }

        [HttpPost("DeleteCuenta")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCuenta([FromForm] int id)
        {
            try
            {
                DeleteApi(id);
                
                TempData["Mensaje"] = "La cuenta se eliminó correctamente.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [HttpDelete("Delete")]
        public IActionResult DeleteApi(int id)
        {
            try
            {
                ResponseModel response = new ResponseModel();
                var cuenta = _cuentaRepo.GetItem(id);

                if (cuenta == null)
                {
                    return NotFound();
                }
                _cuentaRepo.Delete(cuenta);

                response.ErrorId = 0;
                response.ErrorMensaje = "La cuenta se eliminó correctamente.";
                response.root.Add(cuenta);

                return Ok(response);
            }
            catch (Exception ex)
            {
                return Ok(new ResponseModel() { ErrorId = 1, ErrorMensaje = ex.Message });
            }
        }

        private List<SelectListItem> GetTipoCuenta()
        {
            var lstTipoCuenta = new List<SelectListItem>();
            List<TipoCuentaModel> tipoCuentas = _tipoCuentaRepo.GetItems().ToList();

            lstTipoCuenta = tipoCuentas.Select(tp => new SelectListItem() { Value = tp.Id.ToString(), Text = tp.Valor }).ToList();

            return lstTipoCuenta;
        }

        private List<SelectListItem> GetCliente()
        {
            var lstCliente = new List<SelectListItem>();
            List<ClienteModel> Clientes = _clienteRepo.GetItems().ToList();

            lstCliente = Clientes.Select(tp => new SelectListItem() { Value = tp.Id.ToString(), Text = tp.Persona.Nombre }).ToList();

            return lstCliente;
        }
    }
}

Views/Cuentas/Create.cshtml
@model ntt.data.test.luis.pita.Models.CuentaModel

@{
    ViewData["Title"] = "Crear cuenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3>Crear cuenta</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <form method="post" asp-action="CreateView">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Numero" class="control-label"></label>
                    <input asp-for="Numero" class="form-control" />
                    <span asp-validation-for="Numero" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TipoCuentaId" class="control-label"></label>
                    <select asp-for="TipoCuentaId" class="form-control" asp-items="ViewBag.TipoCuentas"></select>
                    <span asp-validation-for="TipoCuentaId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClienteId" class="control-label"></label>
                    <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.Clientes"></select>
                    <span asp-validation-for="ClienteId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Saldo" class="control-label"></label>
                    <input asp-for="Saldo" class="form-control" />
                    <span asp-validation-for="Saldo" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Cuentas/Delete.cshtml
@model ntt.data.test.luis.pita.Models.CuentaModel

@{
    ViewData["Title"] = "Eliminar cuenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3>Eliminar cuenta</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <form method="post" asp-action="DeleteCuenta">

                <input type="hidden" asp-for="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Numero" class="control-label"></label>
                    <input asp-for="Numero" class="form-control" disabled />
                    <span asp-validation-for="Numero" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="TipoCuentaId" class="control-label"></label>
                    <select asp-for="TipoCuentaId" class="form-control" asp-items="ViewBag.TipoCuentas" disabled></select>
                    <span asp-validation-for="TipoCuentaId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ClienteId" class="control-label"></label>
                    <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.Clientes" disabled></select>
                    <span asp-validation-for="ClienteId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Saldo" class="control-label"></label>
                    <input asp-for="Saldo" class="form-control" disabled />
                    <span asp-validation-for="Saldo" class="text-danger"></span>
                </div>

                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Estado" disabled /> @Html.DisplayNameFor(model => model.Estado)
                    </label>
                </div>

                <div class="form-group">
                    <input type="submit" value="Eliminar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Cuentas/Edit.cshtml
@model ntt.data.test.luis.pita.Models.CuentaModel

@{
    ViewData["Title"] = "Editar cuenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3>Editar cuenta</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <form method="post" asp-action="EditView">

                <input type="hidden" asp-for="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Numero" class="control-label"></label>
                    <input asp-for="Numero" class="form-control" />
                    <span asp-validation-for="Numero" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="TipoCuentaId" class="control-label"></label>
                    <select asp-for="TipoCuentaId" class="form-control" asp-items="ViewBag.TipoCuentas"></select>
                    <span asp-validation-for="TipoCuentaId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ClienteId" class="control-label"></label>
                    <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.Clientes"></select>
                    <span asp-validation-for="ClienteId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Saldo" class="control-label"></label>
                    <input asp-for="Saldo" class="form-control" />
                    <span asp-validation-for="Saldo" class="text-danger"></span>
                </div>

                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                    </label>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Cuentas/Index.cshtml
@model IEnumerable<ntt.data.test.luis.pita.Models.CuentaModel>
@{
    ViewData["Title"] = "Lista de Cuentas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["Mensaje"] != null)
    {
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Mensaje"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    }
    <div class="row">
        <div class="col-md-6">
            <h3>Lista de Cuentas</h3>
        </div>
        <div class="col-md-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Cuentas">Agregar cuenta</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.Id)</td>
                        <td>@Html.DisplayNameFor(m => m.Numero)</td>
                        <td>@Html.DisplayNameFor(m => m.TipoCuenta.Valor)</td>
                        <td>@Html.DisplayNameFor(m => m.Cliente.Persona.Nombre)</td>
                        <td>@Html.DisplayNameFor(m => m.Saldo)</td>
                        <td>@Html.DisplayNameFor(m => m.Estado)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Numero</td>
                        <td>@item.TipoCuenta.Valor</td>
                        <td>@item.Cliente.Persona.Nombre</td>
                        <td align="right">@item.Saldo.ToString("0.00")</td>
                        <td align="center">@item.Estado</td>
                        <td>
                            <a asp-controller="Cuentas" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                            <a asp-controller="Cuentas" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros.</p>
        }
    </div>
</div>